In [1]:
import pandas

# Load in the OTHER_PHENOTYPES table

In [3]:
!pwd

/Users/fowler/Dropbox/focus/cryptic/cryptic-misc/data-export/matty

In [4]:
OTHER_PHENOTYPES=pandas.read_pickle("../../../cryptic-tables/DST_MEASUREMENTS.pkl.gz")
OTHER_PHENOTYPES.reset_index(inplace=True)

In [5]:
OTHER_PHENOTYPES.SOURCE.value_counts()

CRyPTIC         178428
SEQTREAT2020     94864
CLIRES2020       69596
NEJM2018         52449
MUMBAI2018       22586
WHO2019          20681
LID2015          19341
PHE2019          18368
Name: SOURCE, dtype: int64

In [6]:
OTHER_PHENOTYPES.DRUG.value_counts()

INH    53811
RIF    52958
EMB    43076
KAN    30931
AMI    29122
MXF    28054
PZA    24208
ETH    22665
CFZ    21530
LZD    21449
STM    21178
LEV    18030
BDQ    17278
RFB    17018
OFX    16905
DLM    16862
CAP    16210
PAS    15809
PTO     3384
DCS     2232
CIP     1389
CYC     1340
CLR      537
GFX      245
STX       72
GEN       12
AZM        6
MPM        1
IMI        1
Name: DRUG, dtype: int64

Only include FQs

In [7]:
OP_INH=OTHER_PHENOTYPES.loc[OTHER_PHENOTYPES.DRUG.isin(['INH'])]

In [8]:
OP_INH[:3]

,index,UNIQUEID,DRUG,SOURCE,METHOD_1,METHOD_2,METHOD_3,METHOD_CC,METHOD_MIC,PHENOTYPE
35371,35371,site.08.subj.02TB2317.lab.26597.iso.1,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,0.2,I
35372,35372,site.05.subj.PMK-0936.lab.MK-0386.iso.1,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,1.6,R
35373,35373,site.08.subj.05TB41001.lab.1759.iso.1,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,<=0.025,S

In [9]:
OP_INH.reset_index(inplace=True)

In [11]:
def create_subjid(row):
    return(row['UNIQUEID'].split('.lab.')[0].split('.subj.')[1])

OP_INH['SUBJID']=OP_INH.apply(create_subjid,axis=1)

/var/folders/np/2z_qny9911n2mqth2n63j9y80009px/T/ipykernel_15872/3840728492.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  OP_INH['SUBJID']=OP_INH.apply(create_subjid,axis=1)

In [12]:
OP_INH[:3]

,level_0,index,UNIQUEID,DRUG,SOURCE,METHOD_1,METHOD_2,METHOD_3,METHOD_CC,METHOD_MIC,PHENOTYPE,SUBJID
0,35371,35371,site.08.subj.02TB2317.lab.26597.iso.1,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,0.2,I,02TB2317
1,35372,35372,site.05.subj.PMK-0936.lab.MK-0386.iso.1,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,1.6,R,PMK-0936
2,35373,35373,site.08.subj.05TB41001.lab.1759.iso.1,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,<=0.025,S,05TB41001

In [13]:
OP_INH.set_index('UNIQUEID',inplace=True)

In [14]:
pandas.crosstab(OP_INH.SOURCE,OP_INH.DRUG)

DRUG            INH
SOURCE
CLIRES2020     6215
CRyPTIC       14998
LID2015        3440
MUMBAI2018     1709
NEJM2018      10002
PHE2019        4198
SEQTREAT2020  11007
WHO2019        2242

In [15]:
INH_phenotypes=OP_INH

In [16]:
INH_phenotypes[:3]

,level_0,index,DRUG,SOURCE,METHOD_1,METHOD_2,METHOD_3,METHOD_CC,METHOD_MIC,PHENOTYPE,SUBJID
UNIQUEID,,,,,,,,,,,
site.08.subj.02TB2317.lab.26597.iso.1,35371,35371,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,0.2,I,02TB2317
site.05.subj.PMK-0936.lab.MK-0386.iso.1,35372,35372,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,1.6,R,PMK-0936
site.08.subj.05TB41001.lab.1759.iso.1,35373,35373,INH,CRyPTIC,liquid media,microdilution plate,UKMYC5,0.1,<=0.025,S,05TB41001

In [17]:
INH_phenotypes.METHOD_2.value_counts()

MGIT                   23520
microdilution plate    17564
LJ                      7275
                        2432
middlebrook             1552
Name: METHOD_2, dtype: int64

Create a list of all the samples that have MXF phenotypes

In [18]:
INH_phenotypes.to_csv("INH_DST_MEASUREMENTS.csv")

In [19]:
samples_with_INH_phenotypes=list(INH_phenotypes.index)

In [20]:
print(len(samples_with_INH_phenotypes))

53811

# Now load in the MUTATIONS

In [21]:
%time MUTATIONS=pandas.read_pickle("../../../cryptic-tables-large/MUTATIONS.pkl.gz")

CPU times: user 13min 38s, sys: 1min 9s, total: 14min 48s
Wall time: 15min 5s

In [22]:
MUTATIONS.reset_index(inplace=True)

Quickly subset down to the gyrA and gyrB genes

In [23]:
INH_mutations=MUTATIONS.loc[MUTATIONS.GENE.isin(['ahpC','fabG1','inhA','katG'])]

In [24]:
INH_mutations[:3]

,UNIQUEID,GENE,MUTATION,POSITION,AMINO_ACID_NUMBER,GENOME_INDEX,NUCLEOTIDE_NUMBER,REF,ALT,IS_SNP,...,IS_HET,IS_NULL,IS_FILTER_PASS,ELEMENT_TYPE,MUTATION_TYPE,INDEL_LENGTH,INDEL_1,INDEL_2,SITEID,NUMBER_NUCLEOTIDE_CHANGES
617,site.02.subj.0958.lab.22A197.iso.1,ahpC,g-48a,-48.0,NaN,2726145.0,-48.0,g,a,True,...,False,False,True,GENE,SNP,NaN,,,02,0
983,site.02.subj.0958.lab.22A197.iso.1,katG,E195X,195.0,195.0,NaN,NaN,gag,gax,True,...,False,True,True,GENE,AAM,NaN,,,02,1
984,site.02.subj.0958.lab.22A197.iso.1,katG,V196X,196.0,196.0,NaN,NaN,gtc,gxc,True,...,False,True,True,GENE,AAM,NaN,,,02,1

In [25]:
len(INH_mutations)

138432

In [26]:
def create_subjid(row):
    return(row['UNIQUEID'].split('.lab.')[0].split('.subj.')[1])

INH_mutations["SUBJID"]=INH_mutations.apply(create_subjid,axis=1)

/var/folders/np/2z_qny9911n2mqth2n63j9y80009px/T/ipykernel_15872/3798694122.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  INH_mutations["SUBJID"]=INH_mutations.apply(create_subjid,axis=1)

In [27]:
INH_mutations=INH_mutations.loc[(~INH_mutations.SITEID.isin(['04','13'])) | ((INH_mutations.SITEID=="04") & ((INH_mutations.SUBJID>'02350') | (INH_mutations.SUBJID<'01575')))]

In [28]:
len(INH_mutations)

136469

In [29]:
INH_mutations.set_index("UNIQUEID",inplace=True)

In [30]:
matching_INH_mutations=INH_mutations

In [31]:
len(matching_INH_mutations)

136469

In [32]:
matching_INH_mutations

,GENE,MUTATION,POSITION,AMINO_ACID_NUMBER,GENOME_INDEX,NUCLEOTIDE_NUMBER,REF,ALT,IS_SNP,IS_INDEL,...,IS_NULL,IS_FILTER_PASS,ELEMENT_TYPE,MUTATION_TYPE,INDEL_LENGTH,INDEL_1,INDEL_2,SITEID,NUMBER_NUCLEOTIDE_CHANGES,SUBJID
UNIQUEID,,,,,,,,,,,,,,,,,,,,,
site.02.subj.0958.lab.22A197.iso.1,ahpC,g-48a,-48.0,NaN,2726145.0,-48.0,g,a,True,False,...,False,True,GENE,SNP,NaN,,,02,0,0958
site.02.subj.0958.lab.22A197.iso.1,katG,E195X,195.0,195.0,NaN,NaN,gag,gax,True,False,...,True,True,GENE,AAM,NaN,,,02,1,0958
site.02.subj.0958.lab.22A197.iso.1,katG,V196X,196.0,196.0,NaN,NaN,gtc,gxc,True,False,...,True,True,GENE,AAM,NaN,,,02,1,0958
site.02.subj.0958.lab.22A197.iso.1,katG,Y197X,197.0,197.0,NaN,NaN,tat,xat,True,False,...,True,True,GENE,AAM,NaN,,,02,1,0958
site.02.subj.0958.lab.22A197.iso.1,katG,W198X,198.0,198.0,NaN,NaN,tgg,txx,True,False,...,True,True,GENE,AAM,NaN,,,02,2,0958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
site.10.subj.YA00008913.lab.YA00008913.iso.1,inhA,I194T,194.0,194.0,NaN,NaN,atc,acc,True,False,...,False,True,GENE,AAM,NaN,,,10,1,YA00008913
site.10.subj.YA00008913.lab.YA00008913.iso.1,katG,R463L,463.0,463.0,NaN,NaN,cgg,ctg,True,False,...,False,True,GENE,AAM,NaN,,,10,1,YA00008913
site.10.subj.YA00166043.lab.YA00166043.iso.1,fabG1,g-17t,-17.0,NaN,1673423.0,-17.0,g,t,True,False,...,False,True,GENE,SNP,NaN,,,10,0,YA00166043
site.10.subj.YA00166043.lab.YA00166043.iso.1,katG,S315T,315.0,315.0,NaN,NaN,agc,acc,True,False,...,False,True,GENE,AAM,NaN,,,10,1,YA00166043
site.10.subj.YA00166043.lab.YA00166043.iso.1,katG,R463L,463.0,463.0,NaN,NaN,cgg,ctg,True,False,...,False,True,GENE,AAM,NaN,,,10,1,YA00166043

In [33]:
matching_INH_mutations.to_csv("INH_MUTATIONS.csv")

# Finally load in PHENOTYPES

In [35]:
PHENOTYPES=pandas.read_pickle("../../../cryptic-tables/UKMYC_PHENOTYPES.pkl.gz")
PHENOTYPES.reset_index(inplace=True)
PHENOTYPES[:3]

,UNIQUEID,DRUG,PLATEDESIGN,BELONGS_GPI,SITEID,DILUTION,PHENOTYPE_QUALITY,READINGDAY,PRIMARY_DILUTION,PRIMARY_METHOD,AMYGDA_DILUTION,BASHTHEBUG_DILUTION,BASHTHEBUGPRO_DILUTION,PHENOTYPE_DESCRIPTION,BASHTHEBUG_NUMBER_CLASSIFICATIONS,BASHTHEBUGPRO_NUMBER_CLASSIFICATIONS,MIC,LOG2MIC,BINARY_PHENOTYPE
0,site.05.subj.PMFR-0743.lab.MFR-247.iso.1,DLM,UKMYC5,True,05,1.0,HIGH,14,1.0,VZ,1.0,1.0,NaN,"VZ,IM AGREE",11.0,NaN,<=0.015,-6.06,S
1,site.10.subj.YA00033005.lab.YA00033005.iso.1,CFZ,UKMYC5,True,10,3.0,HIGH,14,3.0,VZ,1.0,3.0,NaN,"VZ,BB AGREE",15.0,NaN,0.25,-2.00,S
2,site.06.subj.06TB_1032.lab.06MIL2037.iso.1,MXF,UKMYC6,True,06,3.0,HIGH,14,3.0,VZ,3.0,8.0,NaN,"VZ,IM AGREE",11.0,NaN,0.25,-2.00,S

In [36]:
def create_subjid(row):
    return(row['UNIQUEID'].split('.lab.')[0].split('.subj.')[1])

PHENOTYPES['SUBJID']=PHENOTYPES.apply(create_subjid,axis=1)

In [37]:
PHENOTYPES=PHENOTYPES.loc[(~PHENOTYPES.SITEID.isin(['04','13'])) | ((PHENOTYPES.SITEID=="04") & ((PHENOTYPES.SUBJID<'01575')))]

In [38]:
INH_PHENOTYPES=PHENOTYPES.loc[PHENOTYPES.DRUG.isin(['INH'])]

In [39]:
INH_PHENOTYPES[:3]

,UNIQUEID,DRUG,PLATEDESIGN,BELONGS_GPI,SITEID,DILUTION,PHENOTYPE_QUALITY,READINGDAY,PRIMARY_DILUTION,PRIMARY_METHOD,AMYGDA_DILUTION,BASHTHEBUG_DILUTION,BASHTHEBUGPRO_DILUTION,PHENOTYPE_DESCRIPTION,BASHTHEBUG_NUMBER_CLASSIFICATIONS,BASHTHEBUGPRO_NUMBER_CLASSIFICATIONS,MIC,LOG2MIC,BINARY_PHENOTYPE,SUBJID
4,site.02.subj.1892.lab.2015184043.iso.1,INH,UKMYC6,False,02,1.0,HIGH,14,1.0,VZ,-1.0,1.0,NaN,"VZ,BB AGREE",11.0,NaN,<=0.025,-5.32,S,1892
33,site.08.subj.02TB2317.lab.26597.iso.1,INH,UKMYC5,True,08,4.0,HIGH,14,4.0,VZ,3.0,4.0,NaN,"VZ,BB AGREE",15.0,NaN,0.2,-2.32,I,02TB2317
35,site.05.subj.CA-1446.lab.CO-03069-19.iso.1,INH,UKMYC6,True,05,7.0,HIGH,14,7.0,VZ,7.0,7.0,NaN,"VZ,IM AGREE",11.0,NaN,1.6,0.68,R,CA-1446

In [40]:
INH_PHENOTYPES.to_csv("INH_PHENOTYPES.csv")

In [39]:
# need to have zgrepped gyrA and gyrB from VARIANTS.csv.gz

In [45]:
VARIANTS=pandas.read_csv("FQ_VARIANTS.csv.gz")

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (28) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [46]:
VARIANTS

,UNIQUEID,VARIANT,IS_SNP,REF,ALT,GENOME_INDEX,GENE,ELEMENT_TYPE,MUTATION_TYPE,POSITION,...,INDEL_LENGTH,INDEL_1,INDEL_2,DP,COVERAGE,DPF,FRS,GT_CONF,GT_CONF_PERCENTILE,SITEID
0,site.02.subj.0958.lab.22A197.iso.1,7362g>c,True,g,c,7362,gyrA,GENE,SNP,21.0,...,NaN,None,None,279.0,279,1.0078,1.0000,2283.830078,55.709999,02
1,site.02.subj.0958.lab.22A197.iso.1,7585g>c,True,g,c,7585,gyrA,GENE,SNP,95.0,...,NaN,None,None,274.0,274,0.9897,1.0000,2252.760010,51.680000,02
2,site.02.subj.0958.lab.22A197.iso.1,9304g>a,True,g,a,9304,gyrA,GENE,SNP,668.0,...,NaN,None,None,314.0,314,1.1342,1.0000,2498.909912,79.290001,02
3,site.02.subj.0823.lab.2013241494.iso.1,7362g>c,True,g,c,7362,gyrA,GENE,SNP,21.0,...,NaN,None,None,224.0,224,1.0555,1.0000,1812.589966,65.809998,02
4,site.02.subj.0823.lab.2013241494.iso.1,7585g>c,True,g,c,7585,gyrA,GENE,SNP,95.0,...,NaN,None,None,173.0,173,0.8152,1.0000,1492.219971,13.170000,02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318977,site.10.subj.YA00008913.lab.YA00008913.iso.1,6112g>c,True,g,c,6112,gyrB,GENE,SNP,291.0,...,NaN,None,None,69.0,69,0.9536,1.0000,570.400024,44.889999,10
318978,site.10.subj.YA00023171.lab.YA00023171.iso.1,5520c>t,True,c,t,5520,gyrB,GENE,SNP,94.0,...,NaN,None,None,110.0,110,0.8903,1.0000,926.679993,31.709999,10
318979,site.10.subj.YA00023171.lab.YA00023171.iso.1,7222c>t,True,c,t,7222,gyrB,GENE,SNP,661.0,...,NaN,None,None,155.0,155,1.2545,1.0000,1203.239990,89.440002,10
318980,site.10.subj.YA00044774.lab.YA00044774.iso.1,5520c>t,True,c,t,5520,gyrB,GENE,SNP,94.0,...,NaN,None,None,78.0,78,1.0577,1.0000,629.000000,61.619999,10
318981,site.10.subj.YA00044774.lab.YA00044774.iso.1,7222c>t,True,c,t,7222,gyrB,GENE,SNP,661.0,...,NaN,None,None,86.0,85,1.1662,0.9884,661.250000,68.330002,10

In [47]:
VARIANTS.loc[VARIANTS.IS_INDEL].VARIANT.value_counts()

7158_indel    68
9755_indel    35
6360_indel    20
7215_indel    18
9817_indel    18
              ..
8738_indel     1
6846_indel     1
7831_indel     1
6459_indel     1
9093_indel     1
Name: VARIANT, Length: 72, dtype: int64